export const EMAILS = [
  {
    id: "1234567",
    status: "READ",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Coding Assignment - UI - Sahaj Software Solutions",
    body: "Lipsum text here",
    date: "2/12/21",
  },
  {
    id: "1234545",
    status: "UNREAD",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Sample subject here",
    body: "Lipsum text here",
    date: "2/10/21",
  },
  {
    id: "1234457",
    status: "READ",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Coding Assignment - UI - Sahaj Software Solutions",
    body: "Lipsum text here",
    date: "5/12/21",
  },
  {
    id: "1334567",
    status: "UNREAD",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Sample subject here",
    body: "Lipsum text here",
    date: "2/12/21",
  },
  {
    id: "2234567",
    status: "UNREAD",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Sample subject here",
    body: "Lipsum text here",
    date: "2/12/21",
  },
  {
    id: "1234568",
    status: "UNREAD",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Coding Assignment - UI - Sahaj Software Solutions",
    body: "Lipsum text here",
    date: "2/12/21",
  },
  {
    id: "1234569",
    status: "READ",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Sample subject here",
    body: "Lipsum text here",
    date: "2/12/21",
  },
  {
    id: "1234500",
    status: "UNREAD",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Sample subject here",
    body: "Lipsum text here",
    date: "2/12/21",
  },
  {
    id: "1234565",
    status: "UNREAD",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Sample subject here",
    body: "Lipsum text here",
    date: "2/12/21",
  },
  {
    id: "1234533",
    status: "UNREAD",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Sample subject here",
    body: "Lipsum text here",
    date: "2/12/21",
  },
  {
    id: "1234544",
    status: "UNREAD",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Sample subject here",
    body: "Lipsum text here",
    date: "2/12/21",
  },
  {
    id: "1234522",
    status: "READ",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Coding Assignment - UI - Sahaj Software Solutions",
    body: "Lipsum text here",
    date: "2/12/21",
  },
  {
    id: "1234566",
    status: "READ",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Coding Assignment - UI - Sahaj Software Solutions",
    body: "Lipsum text here",
    date: "2/12/21",
  },
  {
    id: "1234500",
    status: "UNREAD",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Coding Assignment - UI - Sahaj Software Solutions",
    body: "Lipsum text here",
    date: "2/12/21",
  },
];

export const SIDEBAR_OPTIONS = [
  "Inbox",
  "Sent",
  "Starred",
  "Important",
  "Drafts",
];
