export const EMAILS = [
  {
    id: 10,
    status: "READ",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Coding Assignment - UI - Sahaj Software Solutions",
    body: "Lipsum text here",
    date: "2/12/21",
  },
  {
    id: 11,
    status: "UNREAD",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Sample subject here",
    body: "Lipsum text here",
    date: "2/10/21",
  },
  {
    id: 12,
    status: "READ",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Coding Assignment - UI - Sahaj Software Solutions",
    body: "Lipsum text here",
    date: "5/12/21",
  },
  {
    id: 13,
    status: "UNREAD",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Sample subject here",
    body: "Lipsum text here",
    date: "2/12/21",
  },
  {
    id: 14,
    status: "UNREAD",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Sample subject here",
    body: "Lipsum text here",
    date: "2/12/21",
  },
  {
    id: 15,
    status: "UNREAD",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Coding Assignment - UI - Sahaj Software Solutions",
    body: "Lipsum text here",
    date: "2/12/21",
  },
  {
    id: 16,
    status: "READ",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Sample subject here",
    body: "Lipsum text here",
    date: "2/12/21",
  },
  {
    id: 17,
    status: "UNREAD",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Sample subject here",
    body: "Lipsum text here",
    date: "2/12/21",
  },
  {
    id: 18,
    status: "UNREAD",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Sample subject here",
    body: "Lipsum text here",
    date: "2/12/21",
  },
  {
    id: 19,
    status: "UNREAD",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Sample subject here",
    body: "Lipsum text here",
    date: "2/12/21",
  },
  {
    id: 20,
    status: "UNREAD",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Sample subject here",
    body: "Lipsum text here",
    date: "2/12/21",
  },
  {
    id: "21",
    status: "READ",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Coding Assignment - UI - Sahaj Software Solutions",
    body: "Lipsum text here",
    date: "2/12/21",
  },
  {
    id: "22",
    status: "READ",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Coding Assignment - UI - Sahaj Software Solutions",
    body: "Lipsum text here",
    date: "2/12/21",
  },
  {
    id: "23",
    status: "UNREAD",
    from: "aakashraina9@gmail.com",
    to: ["test@gmail.com", "mockdata@gmail.com"],
    cc: ["test@gmail.com", "mockdata@gmail.com"],
    subject: "Coding Assignment - UI - Sahaj Software Solutions",
    body: "Lipsum text here",
    date: "2/12/21",
  },
];

export const SIDEBAR_OPTIONS = [
  "Inbox",
  "Sent",
  "Starred",
  "Important",
  "Drafts",
];

export const credentials = {
  username: "aakash",
  passwd: "12345",
};
